CREATE TABLE signups (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  psn VARCHAR(100) NOT NULL,
  position VARCHAR(50) NOT NULL,
  availability VARCHAR(100) NOT NULL,
  color VARCHAR(50) NOT NULL,
  submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
